// This component is responsible for safely rendering the JSON content
// generated by the Slate.js editor into styled React components.

import React from 'react';
import { Descendant, Text as SlateText } from 'slate';
import { CustomElement } from '@/lib/slate-types';

interface RichTextRendererProps {
  content?: string;
}

// Component to render a single Slate node
const Node = ({ node }: { node: Descendant }): JSX.Element => {
    if (SlateText.isText(node)) {
        let leaf: JSX.Element | string = node.text;

        if (node.bold) {
            leaf = <strong>{leaf}</strong>;
        }
        if (node.italic) {
            leaf = <em>{leaf}</em>;
        }
        if (node.underline) {
            leaf = <u>{leaf}</u>;
        }
        if (node.code) {
            leaf = <code className="bg-muted text-foreground font-mono text-sm px-1 py-0.5 rounded-sm">{leaf}</code>;
        }
        return <>{leaf}</>;
    }

    const element = node as CustomElement;
    const children = element.children.map((n, i) => <Node key={i} node={n} />);
    const style = { textAlign: element.align };

    switch (element.type) {
        case 'heading-one':
            return <h1 style={style}>{children}</h1>;
        case 'heading-two':
            return <h2 style={style}>{children}</h2>;
        case 'block-quote':
            return <blockquote style={style}>{children}</blockquote>;
        case 'numbered-list':
            return <ol style={style}>{children}</ol>;
        case 'bulleted-list':
            return <ul style={style}>{children}</ul>;
        case 'list-item':
            return <li style={style}>{children}</li>;
        case 'image':
            const imgStyle = {
                width: element.width,
                height: element.height,
                maxWidth: '100%',
                maxHeight: '100%',
            };
            return (
                <div style={style}>
                    <img src={element.url} alt="" style={imgStyle} className="my-4 rounded-md shadow-md" />
                </div>
            );
        case 'paragraph':
        default:
            return <p style={style}>{children}</p>;
    }
};

export const RichTextRenderer: React.FC<RichTextRendererProps> = ({ content }) => {
    if (!content) {
        return null;
    }

    let parsedContent: Descendant[];

    try {
        parsedContent = JSON.parse(content);
    } catch (e) {
        // If it's not valid JSON, treat it as plain text in a paragraph.
        return <p>{content}</p>;
    }

    if (!Array.isArray(parsedContent)) {
        return <p>{content}</p>; // Fallback for invalid structure
    }

    return (
        <div className="prose dark:prose-invert max-w-none">
            {parsedContent.map((node, i) => (
                <Node key={i} node={node} />
            ))}
        </div>
    );
};
